// clk_100.v

// Generated using ACDS version 23.4 79

`timescale 1 ps / 1 ps
module clk_100 (
		input  wire  in_clk,  //  in_clk.clk
		output wire  out_clk  // out_clk.clk
	);

	assign out_clk = in_clk;

endmodule
