// qsys_top_altera_mm_interconnect_1920_i72dmty.v

// This file was auto-generated from altera_mm_interconnect_hw.tcl.  If you edit it your changes
// will probably be lost.
// 
// Generated using ACDS version 23.4 79

`timescale 1 ps / 1 ps
module qsys_top_altera_mm_interconnect_1920_i72dmty (
		input  wire [4:0]   subsys_periph_ssgdma_host_awid,                                             //                                            subsys_periph_ssgdma_host.awid
		input  wire [63:0]  subsys_periph_ssgdma_host_awaddr,                                           //                                                                     .awaddr
		input  wire [7:0]   subsys_periph_ssgdma_host_awlen,                                            //                                                                     .awlen
		input  wire [2:0]   subsys_periph_ssgdma_host_awsize,                                           //                                                                     .awsize
		input  wire [1:0]   subsys_periph_ssgdma_host_awburst,                                          //                                                                     .awburst
		input  wire [3:0]   subsys_periph_ssgdma_host_awcache,                                          //                                                                     .awcache
		input  wire [2:0]   subsys_periph_ssgdma_host_awprot,                                           //                                                                     .awprot
		input  wire         subsys_periph_ssgdma_host_awvalid,                                          //                                                                     .awvalid
		output wire         subsys_periph_ssgdma_host_awready,                                          //                                                                     .awready
		input  wire [255:0] subsys_periph_ssgdma_host_wdata,                                            //                                                                     .wdata
		input  wire [31:0]  subsys_periph_ssgdma_host_wstrb,                                            //                                                                     .wstrb
		input  wire         subsys_periph_ssgdma_host_wlast,                                            //                                                                     .wlast
		input  wire         subsys_periph_ssgdma_host_wvalid,                                           //                                                                     .wvalid
		output wire         subsys_periph_ssgdma_host_wready,                                           //                                                                     .wready
		output wire [4:0]   subsys_periph_ssgdma_host_bid,                                              //                                                                     .bid
		output wire [1:0]   subsys_periph_ssgdma_host_bresp,                                            //                                                                     .bresp
		output wire         subsys_periph_ssgdma_host_bvalid,                                           //                                                                     .bvalid
		input  wire         subsys_periph_ssgdma_host_bready,                                           //                                                                     .bready
		input  wire [4:0]   subsys_periph_ssgdma_host_arid,                                             //                                                                     .arid
		input  wire [63:0]  subsys_periph_ssgdma_host_araddr,                                           //                                                                     .araddr
		input  wire [7:0]   subsys_periph_ssgdma_host_arlen,                                            //                                                                     .arlen
		input  wire [2:0]   subsys_periph_ssgdma_host_arsize,                                           //                                                                     .arsize
		input  wire [1:0]   subsys_periph_ssgdma_host_arburst,                                          //                                                                     .arburst
		input  wire [3:0]   subsys_periph_ssgdma_host_arcache,                                          //                                                                     .arcache
		input  wire [2:0]   subsys_periph_ssgdma_host_arprot,                                           //                                                                     .arprot
		input  wire         subsys_periph_ssgdma_host_arvalid,                                          //                                                                     .arvalid
		output wire         subsys_periph_ssgdma_host_arready,                                          //                                                                     .arready
		output wire [4:0]   subsys_periph_ssgdma_host_rid,                                              //                                                                     .rid
		output wire [255:0] subsys_periph_ssgdma_host_rdata,                                            //                                                                     .rdata
		output wire [1:0]   subsys_periph_ssgdma_host_rresp,                                            //                                                                     .rresp
		output wire         subsys_periph_ssgdma_host_rlast,                                            //                                                                     .rlast
		output wire         subsys_periph_ssgdma_host_rvalid,                                           //                                                                     .rvalid
		input  wire         subsys_periph_ssgdma_host_rready,                                           //                                                                     .rready
		output wire [4:0]   subsys_hps_fpga2hps_awid,                                                   //                                                  subsys_hps_fpga2hps.awid
		output wire [31:0]  subsys_hps_fpga2hps_awaddr,                                                 //                                                                     .awaddr
		output wire [7:0]   subsys_hps_fpga2hps_awlen,                                                  //                                                                     .awlen
		output wire [2:0]   subsys_hps_fpga2hps_awsize,                                                 //                                                                     .awsize
		output wire [1:0]   subsys_hps_fpga2hps_awburst,                                                //                                                                     .awburst
		output wire [0:0]   subsys_hps_fpga2hps_awlock,                                                 //                                                                     .awlock
		output wire [3:0]   subsys_hps_fpga2hps_awcache,                                                //                                                                     .awcache
		output wire [2:0]   subsys_hps_fpga2hps_awprot,                                                 //                                                                     .awprot
		output wire [7:0]   subsys_hps_fpga2hps_awuser,                                                 //                                                                     .awuser
		output wire [3:0]   subsys_hps_fpga2hps_awqos,                                                  //                                                                     .awqos
		output wire [3:0]   subsys_hps_fpga2hps_awregion,                                               //                                                                     .awregion
		output wire         subsys_hps_fpga2hps_awvalid,                                                //                                                                     .awvalid
		input  wire         subsys_hps_fpga2hps_awready,                                                //                                                                     .awready
		output wire [255:0] subsys_hps_fpga2hps_wdata,                                                  //                                                                     .wdata
		output wire [31:0]  subsys_hps_fpga2hps_wstrb,                                                  //                                                                     .wstrb
		output wire         subsys_hps_fpga2hps_wlast,                                                  //                                                                     .wlast
		output wire         subsys_hps_fpga2hps_wvalid,                                                 //                                                                     .wvalid
		output wire [7:0]   subsys_hps_fpga2hps_wuser,                                                  //                                                                     .wuser
		input  wire         subsys_hps_fpga2hps_wready,                                                 //                                                                     .wready
		input  wire [4:0]   subsys_hps_fpga2hps_bid,                                                    //                                                                     .bid
		input  wire [1:0]   subsys_hps_fpga2hps_bresp,                                                  //                                                                     .bresp
		input  wire [7:0]   subsys_hps_fpga2hps_buser,                                                  //                                                                     .buser
		input  wire         subsys_hps_fpga2hps_bvalid,                                                 //                                                                     .bvalid
		output wire         subsys_hps_fpga2hps_bready,                                                 //                                                                     .bready
		output wire [4:0]   subsys_hps_fpga2hps_arid,                                                   //                                                                     .arid
		output wire [31:0]  subsys_hps_fpga2hps_araddr,                                                 //                                                                     .araddr
		output wire [7:0]   subsys_hps_fpga2hps_arlen,                                                  //                                                                     .arlen
		output wire [2:0]   subsys_hps_fpga2hps_arsize,                                                 //                                                                     .arsize
		output wire [1:0]   subsys_hps_fpga2hps_arburst,                                                //                                                                     .arburst
		output wire [0:0]   subsys_hps_fpga2hps_arlock,                                                 //                                                                     .arlock
		output wire [3:0]   subsys_hps_fpga2hps_arcache,                                                //                                                                     .arcache
		output wire [2:0]   subsys_hps_fpga2hps_arprot,                                                 //                                                                     .arprot
		output wire [7:0]   subsys_hps_fpga2hps_aruser,                                                 //                                                                     .aruser
		output wire [3:0]   subsys_hps_fpga2hps_arqos,                                                  //                                                                     .arqos
		output wire [3:0]   subsys_hps_fpga2hps_arregion,                                               //                                                                     .arregion
		output wire         subsys_hps_fpga2hps_arvalid,                                                //                                                                     .arvalid
		input  wire         subsys_hps_fpga2hps_arready,                                                //                                                                     .arready
		input  wire [4:0]   subsys_hps_fpga2hps_rid,                                                    //                                                                     .rid
		input  wire [255:0] subsys_hps_fpga2hps_rdata,                                                  //                                                                     .rdata
		input  wire [1:0]   subsys_hps_fpga2hps_rresp,                                                  //                                                                     .rresp
		input  wire         subsys_hps_fpga2hps_rlast,                                                  //                                                                     .rlast
		input  wire         subsys_hps_fpga2hps_rvalid,                                                 //                                                                     .rvalid
		output wire         subsys_hps_fpga2hps_rready,                                                 //                                                                     .rready
		input  wire [7:0]   subsys_hps_fpga2hps_ruser,                                                  //                                                                     .ruser
		input  wire         subsys_periph_ssgdma_host_translator_clk_reset_reset_bridge_in_reset_reset, // subsys_periph_ssgdma_host_translator_clk_reset_reset_bridge_in_reset.reset
		input  wire         clk_100_out_clk_clk                                                         //                                                      clk_100_out_clk.clk
	);

	wire    [7:0] subsys_periph_ssgdma_host_translator_m0_ruser;    // subsys_hps_fpga2hps_translator:s0_ruser -> subsys_periph_ssgdma_host_translator:m0_ruser
	wire    [7:0] subsys_periph_ssgdma_host_translator_m0_wuser;    // subsys_periph_ssgdma_host_translator:m0_wuser -> subsys_hps_fpga2hps_translator:s0_wuser
	wire    [1:0] subsys_periph_ssgdma_host_translator_m0_awburst;  // subsys_periph_ssgdma_host_translator:m0_awburst -> subsys_hps_fpga2hps_translator:s0_awburst
	wire    [3:0] subsys_periph_ssgdma_host_translator_m0_arregion; // subsys_periph_ssgdma_host_translator:m0_arregion -> subsys_hps_fpga2hps_translator:s0_arregion
	wire    [7:0] subsys_periph_ssgdma_host_translator_m0_awuser;   // subsys_periph_ssgdma_host_translator:m0_awuser -> subsys_hps_fpga2hps_translator:s0_awuser
	wire    [7:0] subsys_periph_ssgdma_host_translator_m0_arlen;    // subsys_periph_ssgdma_host_translator:m0_arlen -> subsys_hps_fpga2hps_translator:s0_arlen
	wire    [3:0] subsys_periph_ssgdma_host_translator_m0_arqos;    // subsys_periph_ssgdma_host_translator:m0_arqos -> subsys_hps_fpga2hps_translator:s0_arqos
	wire   [31:0] subsys_periph_ssgdma_host_translator_m0_wstrb;    // subsys_periph_ssgdma_host_translator:m0_wstrb -> subsys_hps_fpga2hps_translator:s0_wstrb
	wire          subsys_periph_ssgdma_host_translator_m0_wready;   // subsys_hps_fpga2hps_translator:s0_wready -> subsys_periph_ssgdma_host_translator:m0_wready
	wire    [4:0] subsys_periph_ssgdma_host_translator_m0_rid;      // subsys_hps_fpga2hps_translator:s0_rid -> subsys_periph_ssgdma_host_translator:m0_rid
	wire          subsys_periph_ssgdma_host_translator_m0_rready;   // subsys_periph_ssgdma_host_translator:m0_rready -> subsys_hps_fpga2hps_translator:s0_rready
	wire    [7:0] subsys_periph_ssgdma_host_translator_m0_awlen;    // subsys_periph_ssgdma_host_translator:m0_awlen -> subsys_hps_fpga2hps_translator:s0_awlen
	wire    [3:0] subsys_periph_ssgdma_host_translator_m0_awqos;    // subsys_periph_ssgdma_host_translator:m0_awqos -> subsys_hps_fpga2hps_translator:s0_awqos
	wire    [3:0] subsys_periph_ssgdma_host_translator_m0_arcache;  // subsys_periph_ssgdma_host_translator:m0_arcache -> subsys_hps_fpga2hps_translator:s0_arcache
	wire          subsys_periph_ssgdma_host_translator_m0_wvalid;   // subsys_periph_ssgdma_host_translator:m0_wvalid -> subsys_hps_fpga2hps_translator:s0_wvalid
	wire   [63:0] subsys_periph_ssgdma_host_translator_m0_araddr;   // subsys_periph_ssgdma_host_translator:m0_araddr -> subsys_hps_fpga2hps_translator:s0_araddr
	wire    [2:0] subsys_periph_ssgdma_host_translator_m0_arprot;   // subsys_periph_ssgdma_host_translator:m0_arprot -> subsys_hps_fpga2hps_translator:s0_arprot
	wire    [2:0] subsys_periph_ssgdma_host_translator_m0_awprot;   // subsys_periph_ssgdma_host_translator:m0_awprot -> subsys_hps_fpga2hps_translator:s0_awprot
	wire  [255:0] subsys_periph_ssgdma_host_translator_m0_wdata;    // subsys_periph_ssgdma_host_translator:m0_wdata -> subsys_hps_fpga2hps_translator:s0_wdata
	wire          subsys_periph_ssgdma_host_translator_m0_arvalid;  // subsys_periph_ssgdma_host_translator:m0_arvalid -> subsys_hps_fpga2hps_translator:s0_arvalid
	wire    [3:0] subsys_periph_ssgdma_host_translator_m0_awcache;  // subsys_periph_ssgdma_host_translator:m0_awcache -> subsys_hps_fpga2hps_translator:s0_awcache
	wire    [4:0] subsys_periph_ssgdma_host_translator_m0_arid;     // subsys_periph_ssgdma_host_translator:m0_arid -> subsys_hps_fpga2hps_translator:s0_arid
	wire    [0:0] subsys_periph_ssgdma_host_translator_m0_arlock;   // subsys_periph_ssgdma_host_translator:m0_arlock -> subsys_hps_fpga2hps_translator:s0_arlock
	wire    [0:0] subsys_periph_ssgdma_host_translator_m0_awlock;   // subsys_periph_ssgdma_host_translator:m0_awlock -> subsys_hps_fpga2hps_translator:s0_awlock
	wire   [63:0] subsys_periph_ssgdma_host_translator_m0_awaddr;   // subsys_periph_ssgdma_host_translator:m0_awaddr -> subsys_hps_fpga2hps_translator:s0_awaddr
	wire    [1:0] subsys_periph_ssgdma_host_translator_m0_bresp;    // subsys_hps_fpga2hps_translator:s0_bresp -> subsys_periph_ssgdma_host_translator:m0_bresp
	wire          subsys_periph_ssgdma_host_translator_m0_arready;  // subsys_hps_fpga2hps_translator:s0_arready -> subsys_periph_ssgdma_host_translator:m0_arready
	wire  [255:0] subsys_periph_ssgdma_host_translator_m0_rdata;    // subsys_hps_fpga2hps_translator:s0_rdata -> subsys_periph_ssgdma_host_translator:m0_rdata
	wire          subsys_periph_ssgdma_host_translator_m0_awready;  // subsys_hps_fpga2hps_translator:s0_awready -> subsys_periph_ssgdma_host_translator:m0_awready
	wire    [1:0] subsys_periph_ssgdma_host_translator_m0_arburst;  // subsys_periph_ssgdma_host_translator:m0_arburst -> subsys_hps_fpga2hps_translator:s0_arburst
	wire    [2:0] subsys_periph_ssgdma_host_translator_m0_arsize;   // subsys_periph_ssgdma_host_translator:m0_arsize -> subsys_hps_fpga2hps_translator:s0_arsize
	wire          subsys_periph_ssgdma_host_translator_m0_bready;   // subsys_periph_ssgdma_host_translator:m0_bready -> subsys_hps_fpga2hps_translator:s0_bready
	wire          subsys_periph_ssgdma_host_translator_m0_rlast;    // subsys_hps_fpga2hps_translator:s0_rlast -> subsys_periph_ssgdma_host_translator:m0_rlast
	wire          subsys_periph_ssgdma_host_translator_m0_wlast;    // subsys_periph_ssgdma_host_translator:m0_wlast -> subsys_hps_fpga2hps_translator:s0_wlast
	wire    [3:0] subsys_periph_ssgdma_host_translator_m0_awregion; // subsys_periph_ssgdma_host_translator:m0_awregion -> subsys_hps_fpga2hps_translator:s0_awregion
	wire    [7:0] subsys_periph_ssgdma_host_translator_m0_buser;    // subsys_hps_fpga2hps_translator:s0_buser -> subsys_periph_ssgdma_host_translator:m0_buser
	wire    [1:0] subsys_periph_ssgdma_host_translator_m0_rresp;    // subsys_hps_fpga2hps_translator:s0_rresp -> subsys_periph_ssgdma_host_translator:m0_rresp
	wire    [4:0] subsys_periph_ssgdma_host_translator_m0_awid;     // subsys_periph_ssgdma_host_translator:m0_awid -> subsys_hps_fpga2hps_translator:s0_awid
	wire    [4:0] subsys_periph_ssgdma_host_translator_m0_bid;      // subsys_hps_fpga2hps_translator:s0_bid -> subsys_periph_ssgdma_host_translator:m0_bid
	wire          subsys_periph_ssgdma_host_translator_m0_bvalid;   // subsys_hps_fpga2hps_translator:s0_bvalid -> subsys_periph_ssgdma_host_translator:m0_bvalid
	wire    [2:0] subsys_periph_ssgdma_host_translator_m0_awsize;   // subsys_periph_ssgdma_host_translator:m0_awsize -> subsys_hps_fpga2hps_translator:s0_awsize
	wire          subsys_periph_ssgdma_host_translator_m0_awvalid;  // subsys_periph_ssgdma_host_translator:m0_awvalid -> subsys_hps_fpga2hps_translator:s0_awvalid
	wire    [7:0] subsys_periph_ssgdma_host_translator_m0_aruser;   // subsys_periph_ssgdma_host_translator:m0_aruser -> subsys_hps_fpga2hps_translator:s0_aruser
	wire          subsys_periph_ssgdma_host_translator_m0_rvalid;   // subsys_hps_fpga2hps_translator:s0_rvalid -> subsys_periph_ssgdma_host_translator:m0_rvalid

	qsys_top_altera_merlin_axi_translator_1931_d46vvwa #(
		.USE_S0_AWID                       (1),
		.USE_S0_AWREGION                   (0),
		.USE_M0_AWREGION                   (1),
		.USE_S0_AWLEN                      (1),
		.USE_S0_AWSIZE                     (1),
		.USE_S0_AWBURST                    (1),
		.USE_S0_AWLOCK                     (0),
		.USE_M0_AWLOCK                     (1),
		.USE_S0_AWCACHE                    (1),
		.USE_M0_AWCACHE                    (1),
		.USE_M0_AWPROT                     (1),
		.USE_S0_AWQOS                      (0),
		.USE_M0_AWQOS                      (1),
		.USE_S0_WSTRB                      (1),
		.USE_M0_WLAST                      (1),
		.USE_S0_BID                        (1),
		.USE_S0_BRESP                      (1),
		.USE_M0_BRESP                      (1),
		.USE_S0_ARID                       (1),
		.USE_S0_ARREGION                   (0),
		.USE_M0_ARREGION                   (1),
		.USE_S0_ARLEN                      (1),
		.USE_S0_ARSIZE                     (1),
		.USE_S0_ARBURST                    (1),
		.USE_S0_ARLOCK                     (0),
		.USE_M0_ARLOCK                     (1),
		.USE_M0_ARCACHE                    (1),
		.USE_M0_ARQOS                      (1),
		.USE_M0_ARPROT                     (1),
		.USE_S0_ARCACHE                    (1),
		.USE_S0_ARQOS                      (0),
		.USE_S0_RID                        (1),
		.USE_S0_RRESP                      (1),
		.USE_M0_RRESP                      (1),
		.USE_S0_RLAST                      (1),
		.M0_ID_WIDTH                       (5),
		.DATA_WIDTH                        (256),
		.M0_SAI_WIDTH                      (4),
		.S0_SAI_WIDTH                      (4),
		.M0_USER_ADDRCHK_WIDTH             (4),
		.S0_USER_ADDRCHK_WIDTH             (4),
		.S0_ID_WIDTH                       (5),
		.M0_ADDR_WIDTH                     (64),
		.S0_WRITE_ADDR_USER_WIDTH          (1),
		.S0_READ_ADDR_USER_WIDTH           (1),
		.M0_WRITE_ADDR_USER_WIDTH          (8),
		.M0_READ_ADDR_USER_WIDTH           (8),
		.S0_WRITE_DATA_USER_WIDTH          (1),
		.S0_WRITE_RESPONSE_DATA_USER_WIDTH (1),
		.S0_READ_DATA_USER_WIDTH           (1),
		.M0_WRITE_DATA_USER_WIDTH          (8),
		.M0_WRITE_RESPONSE_DATA_USER_WIDTH (8),
		.M0_READ_DATA_USER_WIDTH           (8),
		.S0_ADDR_WIDTH                     (64),
		.USE_S0_AWUSER                     (0),
		.USE_S0_ARUSER                     (0),
		.USE_S0_WUSER                      (0),
		.USE_S0_RUSER                      (0),
		.USE_S0_BUSER                      (0),
		.USE_M0_AWUSER                     (1),
		.USE_M0_ARUSER                     (1),
		.USE_M0_WUSER                      (1),
		.USE_M0_RUSER                      (1),
		.USE_M0_BUSER                      (1),
		.M0_AXI_VERSION                    ("AXI4"),
		.M0_BURST_LENGTH_WIDTH             (8),
		.S0_BURST_LENGTH_WIDTH             (8),
		.M0_LOCK_WIDTH                     (1),
		.S0_LOCK_WIDTH                     (1),
		.S0_AXI_VERSION                    ("AXI4"),
		.ACE_LITE_SUPPORT                  (0),
		.USE_M0_AWUSER_ADDRCHK             (0),
		.USE_M0_AWUSER_SAI                 (0),
		.USE_M0_ARUSER_ADDRCHK             (0),
		.USE_M0_ARUSER_SAI                 (0),
		.USE_M0_WUSER_DATACHK              (0),
		.USE_M0_WUSER_POISON               (0),
		.USE_M0_RUSER_DATACHK              (0),
		.USE_M0_RUSER_POISON               (0),
		.USE_S0_AWUSER_ADDRCHK             (0),
		.USE_S0_AWUSER_SAI                 (0),
		.USE_S0_ARUSER_ADDRCHK             (0),
		.USE_S0_ARUSER_SAI                 (0),
		.USE_S0_WUSER_DATACHK              (0),
		.USE_S0_WUSER_POISON               (0),
		.USE_S0_RUSER_DATACHK              (0),
		.USE_S0_RUSER_POISON               (0),
		.ROLE_BASED_USER                   (0)
	) subsys_periph_ssgdma_host_translator (
		.aclk              (clk_100_out_clk_clk),                                                         //   input,    width = 1,       clk.clk
		.aresetn           (~subsys_periph_ssgdma_host_translator_clk_reset_reset_bridge_in_reset_reset), //   input,    width = 1, clk_reset.reset_n
		.m0_awid           (subsys_periph_ssgdma_host_translator_m0_awid),                                //  output,    width = 5,        m0.awid
		.m0_awaddr         (subsys_periph_ssgdma_host_translator_m0_awaddr),                              //  output,   width = 64,          .awaddr
		.m0_awlen          (subsys_periph_ssgdma_host_translator_m0_awlen),                               //  output,    width = 8,          .awlen
		.m0_awsize         (subsys_periph_ssgdma_host_translator_m0_awsize),                              //  output,    width = 3,          .awsize
		.m0_awburst        (subsys_periph_ssgdma_host_translator_m0_awburst),                             //  output,    width = 2,          .awburst
		.m0_awlock         (subsys_periph_ssgdma_host_translator_m0_awlock),                              //  output,    width = 1,          .awlock
		.m0_awcache        (subsys_periph_ssgdma_host_translator_m0_awcache),                             //  output,    width = 4,          .awcache
		.m0_awprot         (subsys_periph_ssgdma_host_translator_m0_awprot),                              //  output,    width = 3,          .awprot
		.m0_awuser         (subsys_periph_ssgdma_host_translator_m0_awuser),                              //  output,    width = 8,          .awuser
		.m0_awqos          (subsys_periph_ssgdma_host_translator_m0_awqos),                               //  output,    width = 4,          .awqos
		.m0_awregion       (subsys_periph_ssgdma_host_translator_m0_awregion),                            //  output,    width = 4,          .awregion
		.m0_awvalid        (subsys_periph_ssgdma_host_translator_m0_awvalid),                             //  output,    width = 1,          .awvalid
		.m0_awready        (subsys_periph_ssgdma_host_translator_m0_awready),                             //   input,    width = 1,          .awready
		.m0_wdata          (subsys_periph_ssgdma_host_translator_m0_wdata),                               //  output,  width = 256,          .wdata
		.m0_wstrb          (subsys_periph_ssgdma_host_translator_m0_wstrb),                               //  output,   width = 32,          .wstrb
		.m0_wlast          (subsys_periph_ssgdma_host_translator_m0_wlast),                               //  output,    width = 1,          .wlast
		.m0_wvalid         (subsys_periph_ssgdma_host_translator_m0_wvalid),                              //  output,    width = 1,          .wvalid
		.m0_wuser          (subsys_periph_ssgdma_host_translator_m0_wuser),                               //  output,    width = 8,          .wuser
		.m0_wready         (subsys_periph_ssgdma_host_translator_m0_wready),                              //   input,    width = 1,          .wready
		.m0_bid            (subsys_periph_ssgdma_host_translator_m0_bid),                                 //   input,    width = 5,          .bid
		.m0_bresp          (subsys_periph_ssgdma_host_translator_m0_bresp),                               //   input,    width = 2,          .bresp
		.m0_buser          (subsys_periph_ssgdma_host_translator_m0_buser),                               //   input,    width = 8,          .buser
		.m0_bvalid         (subsys_periph_ssgdma_host_translator_m0_bvalid),                              //   input,    width = 1,          .bvalid
		.m0_bready         (subsys_periph_ssgdma_host_translator_m0_bready),                              //  output,    width = 1,          .bready
		.m0_arid           (subsys_periph_ssgdma_host_translator_m0_arid),                                //  output,    width = 5,          .arid
		.m0_araddr         (subsys_periph_ssgdma_host_translator_m0_araddr),                              //  output,   width = 64,          .araddr
		.m0_arlen          (subsys_periph_ssgdma_host_translator_m0_arlen),                               //  output,    width = 8,          .arlen
		.m0_arsize         (subsys_periph_ssgdma_host_translator_m0_arsize),                              //  output,    width = 3,          .arsize
		.m0_arburst        (subsys_periph_ssgdma_host_translator_m0_arburst),                             //  output,    width = 2,          .arburst
		.m0_arlock         (subsys_periph_ssgdma_host_translator_m0_arlock),                              //  output,    width = 1,          .arlock
		.m0_arcache        (subsys_periph_ssgdma_host_translator_m0_arcache),                             //  output,    width = 4,          .arcache
		.m0_arprot         (subsys_periph_ssgdma_host_translator_m0_arprot),                              //  output,    width = 3,          .arprot
		.m0_aruser         (subsys_periph_ssgdma_host_translator_m0_aruser),                              //  output,    width = 8,          .aruser
		.m0_arqos          (subsys_periph_ssgdma_host_translator_m0_arqos),                               //  output,    width = 4,          .arqos
		.m0_arregion       (subsys_periph_ssgdma_host_translator_m0_arregion),                            //  output,    width = 4,          .arregion
		.m0_arvalid        (subsys_periph_ssgdma_host_translator_m0_arvalid),                             //  output,    width = 1,          .arvalid
		.m0_arready        (subsys_periph_ssgdma_host_translator_m0_arready),                             //   input,    width = 1,          .arready
		.m0_rid            (subsys_periph_ssgdma_host_translator_m0_rid),                                 //   input,    width = 5,          .rid
		.m0_rdata          (subsys_periph_ssgdma_host_translator_m0_rdata),                               //   input,  width = 256,          .rdata
		.m0_rresp          (subsys_periph_ssgdma_host_translator_m0_rresp),                               //   input,    width = 2,          .rresp
		.m0_rlast          (subsys_periph_ssgdma_host_translator_m0_rlast),                               //   input,    width = 1,          .rlast
		.m0_rvalid         (subsys_periph_ssgdma_host_translator_m0_rvalid),                              //   input,    width = 1,          .rvalid
		.m0_rready         (subsys_periph_ssgdma_host_translator_m0_rready),                              //  output,    width = 1,          .rready
		.m0_ruser          (subsys_periph_ssgdma_host_translator_m0_ruser),                               //   input,    width = 8,          .ruser
		.s0_awid           (subsys_periph_ssgdma_host_awid),                                              //   input,    width = 5,        s0.awid
		.s0_awaddr         (subsys_periph_ssgdma_host_awaddr),                                            //   input,   width = 64,          .awaddr
		.s0_awlen          (subsys_periph_ssgdma_host_awlen),                                             //   input,    width = 8,          .awlen
		.s0_awsize         (subsys_periph_ssgdma_host_awsize),                                            //   input,    width = 3,          .awsize
		.s0_awburst        (subsys_periph_ssgdma_host_awburst),                                           //   input,    width = 2,          .awburst
		.s0_awcache        (subsys_periph_ssgdma_host_awcache),                                           //   input,    width = 4,          .awcache
		.s0_awprot         (subsys_periph_ssgdma_host_awprot),                                            //   input,    width = 3,          .awprot
		.s0_awvalid        (subsys_periph_ssgdma_host_awvalid),                                           //   input,    width = 1,          .awvalid
		.s0_awready        (subsys_periph_ssgdma_host_awready),                                           //  output,    width = 1,          .awready
		.s0_wdata          (subsys_periph_ssgdma_host_wdata),                                             //   input,  width = 256,          .wdata
		.s0_wstrb          (subsys_periph_ssgdma_host_wstrb),                                             //   input,   width = 32,          .wstrb
		.s0_wlast          (subsys_periph_ssgdma_host_wlast),                                             //   input,    width = 1,          .wlast
		.s0_wvalid         (subsys_periph_ssgdma_host_wvalid),                                            //   input,    width = 1,          .wvalid
		.s0_wready         (subsys_periph_ssgdma_host_wready),                                            //  output,    width = 1,          .wready
		.s0_bid            (subsys_periph_ssgdma_host_bid),                                               //  output,    width = 5,          .bid
		.s0_bresp          (subsys_periph_ssgdma_host_bresp),                                             //  output,    width = 2,          .bresp
		.s0_bvalid         (subsys_periph_ssgdma_host_bvalid),                                            //  output,    width = 1,          .bvalid
		.s0_bready         (subsys_periph_ssgdma_host_bready),                                            //   input,    width = 1,          .bready
		.s0_arid           (subsys_periph_ssgdma_host_arid),                                              //   input,    width = 5,          .arid
		.s0_araddr         (subsys_periph_ssgdma_host_araddr),                                            //   input,   width = 64,          .araddr
		.s0_arlen          (subsys_periph_ssgdma_host_arlen),                                             //   input,    width = 8,          .arlen
		.s0_arsize         (subsys_periph_ssgdma_host_arsize),                                            //   input,    width = 3,          .arsize
		.s0_arburst        (subsys_periph_ssgdma_host_arburst),                                           //   input,    width = 2,          .arburst
		.s0_arcache        (subsys_periph_ssgdma_host_arcache),                                           //   input,    width = 4,          .arcache
		.s0_arprot         (subsys_periph_ssgdma_host_arprot),                                            //   input,    width = 3,          .arprot
		.s0_arvalid        (subsys_periph_ssgdma_host_arvalid),                                           //   input,    width = 1,          .arvalid
		.s0_arready        (subsys_periph_ssgdma_host_arready),                                           //  output,    width = 1,          .arready
		.s0_rid            (subsys_periph_ssgdma_host_rid),                                               //  output,    width = 5,          .rid
		.s0_rdata          (subsys_periph_ssgdma_host_rdata),                                             //  output,  width = 256,          .rdata
		.s0_rresp          (subsys_periph_ssgdma_host_rresp),                                             //  output,    width = 2,          .rresp
		.s0_rlast          (subsys_periph_ssgdma_host_rlast),                                             //  output,    width = 1,          .rlast
		.s0_rvalid         (subsys_periph_ssgdma_host_rvalid),                                            //  output,    width = 1,          .rvalid
		.s0_rready         (subsys_periph_ssgdma_host_rready),                                            //   input,    width = 1,          .rready
		.m0_awuser_addrchk (),                                                                            // (terminated),                         
		.m0_awuser_sai     (),                                                                            // (terminated),                         
		.m0_wuser_datachk  (),                                                                            // (terminated),                         
		.m0_wuser_poison   (),                                                                            // (terminated),                         
		.m0_aruser_addrchk (),                                                                            // (terminated),                         
		.m0_aruser_sai     (),                                                                            // (terminated),                         
		.m0_ruser_datachk  (32'b00000000000000000000000000000000),                                        // (terminated),                         
		.m0_ruser_poison   (4'b0000),                                                                     // (terminated),                         
		.s0_awlock         (1'b0),                                                                        // (terminated),                         
		.s0_awuser         (1'b0),                                                                        // (terminated),                         
		.s0_awuser_addrchk (4'b0000),                                                                     // (terminated),                         
		.s0_awuser_sai     (4'b0000),                                                                     // (terminated),                         
		.s0_awqos          (4'b0000),                                                                     // (terminated),                         
		.s0_awregion       (4'b0000),                                                                     // (terminated),                         
		.s0_wuser          (1'b0),                                                                        // (terminated),                         
		.s0_wuser_datachk  (32'b00000000000000000000000000000000),                                        // (terminated),                         
		.s0_wuser_poison   (4'b0000),                                                                     // (terminated),                         
		.s0_buser          (),                                                                            // (terminated),                         
		.s0_arlock         (1'b0),                                                                        // (terminated),                         
		.s0_aruser         (1'b0),                                                                        // (terminated),                         
		.s0_aruser_addrchk (4'b0000),                                                                     // (terminated),                         
		.s0_aruser_sai     (4'b0000),                                                                     // (terminated),                         
		.s0_arqos          (4'b0000),                                                                     // (terminated),                         
		.s0_arregion       (4'b0000),                                                                     // (terminated),                         
		.s0_ruser          (),                                                                            // (terminated),                         
		.s0_ruser_datachk  (),                                                                            // (terminated),                         
		.s0_ruser_poison   (),                                                                            // (terminated),                         
		.s0_wid            (5'b00000),                                                                    // (terminated),                         
		.s0_ardomain       (2'b00),                                                                       // (terminated),                         
		.s0_arsnoop        (4'b0000),                                                                     // (terminated),                         
		.s0_arbar          (2'b00),                                                                       // (terminated),                         
		.s0_awdomain       (2'b00),                                                                       // (terminated),                         
		.s0_awsnoop        (3'b000),                                                                      // (terminated),                         
		.s0_awbar          (2'b00),                                                                       // (terminated),                         
		.s0_awunique       (1'b0),                                                                        // (terminated),                         
		.m0_wid            (),                                                                            // (terminated),                         
		.m0_ardomain       (),                                                                            // (terminated),                         
		.m0_arsnoop        (),                                                                            // (terminated),                         
		.m0_arbar          (),                                                                            // (terminated),                         
		.m0_awdomain       (),                                                                            // (terminated),                         
		.m0_awsnoop        (),                                                                            // (terminated),                         
		.m0_awbar          (),                                                                            // (terminated),                         
		.m0_awunique       ()                                                                             // (terminated),                         
	);

	qsys_top_altera_merlin_axi_translator_1931_d46vvwa #(
		.USE_S0_AWID                       (1),
		.USE_S0_AWREGION                   (1),
		.USE_M0_AWREGION                   (1),
		.USE_S0_AWLEN                      (1),
		.USE_S0_AWSIZE                     (1),
		.USE_S0_AWBURST                    (1),
		.USE_S0_AWLOCK                     (1),
		.USE_M0_AWLOCK                     (1),
		.USE_S0_AWCACHE                    (1),
		.USE_M0_AWCACHE                    (1),
		.USE_M0_AWPROT                     (1),
		.USE_S0_AWQOS                      (1),
		.USE_M0_AWQOS                      (1),
		.USE_S0_WSTRB                      (1),
		.USE_M0_WLAST                      (1),
		.USE_S0_BID                        (1),
		.USE_S0_BRESP                      (1),
		.USE_M0_BRESP                      (1),
		.USE_S0_ARID                       (1),
		.USE_S0_ARREGION                   (1),
		.USE_M0_ARREGION                   (1),
		.USE_S0_ARLEN                      (1),
		.USE_S0_ARSIZE                     (1),
		.USE_S0_ARBURST                    (1),
		.USE_S0_ARLOCK                     (1),
		.USE_M0_ARLOCK                     (1),
		.USE_M0_ARCACHE                    (1),
		.USE_M0_ARQOS                      (1),
		.USE_M0_ARPROT                     (1),
		.USE_S0_ARCACHE                    (1),
		.USE_S0_ARQOS                      (1),
		.USE_S0_RID                        (1),
		.USE_S0_RRESP                      (1),
		.USE_M0_RRESP                      (1),
		.USE_S0_RLAST                      (1),
		.M0_ID_WIDTH                       (5),
		.DATA_WIDTH                        (256),
		.M0_SAI_WIDTH                      (4),
		.S0_SAI_WIDTH                      (4),
		.M0_USER_ADDRCHK_WIDTH             (4),
		.S0_USER_ADDRCHK_WIDTH             (4),
		.S0_ID_WIDTH                       (5),
		.M0_ADDR_WIDTH                     (32),
		.S0_WRITE_ADDR_USER_WIDTH          (8),
		.S0_READ_ADDR_USER_WIDTH           (8),
		.M0_WRITE_ADDR_USER_WIDTH          (8),
		.M0_READ_ADDR_USER_WIDTH           (8),
		.S0_WRITE_DATA_USER_WIDTH          (8),
		.S0_WRITE_RESPONSE_DATA_USER_WIDTH (8),
		.S0_READ_DATA_USER_WIDTH           (8),
		.M0_WRITE_DATA_USER_WIDTH          (8),
		.M0_WRITE_RESPONSE_DATA_USER_WIDTH (8),
		.M0_READ_DATA_USER_WIDTH           (8),
		.S0_ADDR_WIDTH                     (64),
		.USE_S0_AWUSER                     (1),
		.USE_S0_ARUSER                     (1),
		.USE_S0_WUSER                      (1),
		.USE_S0_RUSER                      (1),
		.USE_S0_BUSER                      (1),
		.USE_M0_AWUSER                     (1),
		.USE_M0_ARUSER                     (1),
		.USE_M0_WUSER                      (1),
		.USE_M0_RUSER                      (1),
		.USE_M0_BUSER                      (1),
		.M0_AXI_VERSION                    ("AXI4"),
		.M0_BURST_LENGTH_WIDTH             (8),
		.S0_BURST_LENGTH_WIDTH             (8),
		.M0_LOCK_WIDTH                     (1),
		.S0_LOCK_WIDTH                     (1),
		.S0_AXI_VERSION                    ("AXI4"),
		.ACE_LITE_SUPPORT                  (0),
		.USE_M0_AWUSER_ADDRCHK             (0),
		.USE_M0_AWUSER_SAI                 (0),
		.USE_M0_ARUSER_ADDRCHK             (0),
		.USE_M0_ARUSER_SAI                 (0),
		.USE_M0_WUSER_DATACHK              (0),
		.USE_M0_WUSER_POISON               (0),
		.USE_M0_RUSER_DATACHK              (0),
		.USE_M0_RUSER_POISON               (0),
		.USE_S0_AWUSER_ADDRCHK             (0),
		.USE_S0_AWUSER_SAI                 (0),
		.USE_S0_ARUSER_ADDRCHK             (0),
		.USE_S0_ARUSER_SAI                 (0),
		.USE_S0_WUSER_DATACHK              (0),
		.USE_S0_WUSER_POISON               (0),
		.USE_S0_RUSER_DATACHK              (0),
		.USE_S0_RUSER_POISON               (0),
		.ROLE_BASED_USER                   (0)
	) subsys_hps_fpga2hps_translator (
		.aclk              (clk_100_out_clk_clk),                                                         //   input,    width = 1,       clk.clk
		.aresetn           (~subsys_periph_ssgdma_host_translator_clk_reset_reset_bridge_in_reset_reset), //   input,    width = 1, clk_reset.reset_n
		.m0_awid           (subsys_hps_fpga2hps_awid),                                                    //  output,    width = 5,        m0.awid
		.m0_awaddr         (subsys_hps_fpga2hps_awaddr),                                                  //  output,   width = 32,          .awaddr
		.m0_awlen          (subsys_hps_fpga2hps_awlen),                                                   //  output,    width = 8,          .awlen
		.m0_awsize         (subsys_hps_fpga2hps_awsize),                                                  //  output,    width = 3,          .awsize
		.m0_awburst        (subsys_hps_fpga2hps_awburst),                                                 //  output,    width = 2,          .awburst
		.m0_awlock         (subsys_hps_fpga2hps_awlock),                                                  //  output,    width = 1,          .awlock
		.m0_awcache        (subsys_hps_fpga2hps_awcache),                                                 //  output,    width = 4,          .awcache
		.m0_awprot         (subsys_hps_fpga2hps_awprot),                                                  //  output,    width = 3,          .awprot
		.m0_awuser         (subsys_hps_fpga2hps_awuser),                                                  //  output,    width = 8,          .awuser
		.m0_awqos          (subsys_hps_fpga2hps_awqos),                                                   //  output,    width = 4,          .awqos
		.m0_awregion       (subsys_hps_fpga2hps_awregion),                                                //  output,    width = 4,          .awregion
		.m0_awvalid        (subsys_hps_fpga2hps_awvalid),                                                 //  output,    width = 1,          .awvalid
		.m0_awready        (subsys_hps_fpga2hps_awready),                                                 //   input,    width = 1,          .awready
		.m0_wdata          (subsys_hps_fpga2hps_wdata),                                                   //  output,  width = 256,          .wdata
		.m0_wstrb          (subsys_hps_fpga2hps_wstrb),                                                   //  output,   width = 32,          .wstrb
		.m0_wlast          (subsys_hps_fpga2hps_wlast),                                                   //  output,    width = 1,          .wlast
		.m0_wvalid         (subsys_hps_fpga2hps_wvalid),                                                  //  output,    width = 1,          .wvalid
		.m0_wuser          (subsys_hps_fpga2hps_wuser),                                                   //  output,    width = 8,          .wuser
		.m0_wready         (subsys_hps_fpga2hps_wready),                                                  //   input,    width = 1,          .wready
		.m0_bid            (subsys_hps_fpga2hps_bid),                                                     //   input,    width = 5,          .bid
		.m0_bresp          (subsys_hps_fpga2hps_bresp),                                                   //   input,    width = 2,          .bresp
		.m0_buser          (subsys_hps_fpga2hps_buser),                                                   //   input,    width = 8,          .buser
		.m0_bvalid         (subsys_hps_fpga2hps_bvalid),                                                  //   input,    width = 1,          .bvalid
		.m0_bready         (subsys_hps_fpga2hps_bready),                                                  //  output,    width = 1,          .bready
		.m0_arid           (subsys_hps_fpga2hps_arid),                                                    //  output,    width = 5,          .arid
		.m0_araddr         (subsys_hps_fpga2hps_araddr),                                                  //  output,   width = 32,          .araddr
		.m0_arlen          (subsys_hps_fpga2hps_arlen),                                                   //  output,    width = 8,          .arlen
		.m0_arsize         (subsys_hps_fpga2hps_arsize),                                                  //  output,    width = 3,          .arsize
		.m0_arburst        (subsys_hps_fpga2hps_arburst),                                                 //  output,    width = 2,          .arburst
		.m0_arlock         (subsys_hps_fpga2hps_arlock),                                                  //  output,    width = 1,          .arlock
		.m0_arcache        (subsys_hps_fpga2hps_arcache),                                                 //  output,    width = 4,          .arcache
		.m0_arprot         (subsys_hps_fpga2hps_arprot),                                                  //  output,    width = 3,          .arprot
		.m0_aruser         (subsys_hps_fpga2hps_aruser),                                                  //  output,    width = 8,          .aruser
		.m0_arqos          (subsys_hps_fpga2hps_arqos),                                                   //  output,    width = 4,          .arqos
		.m0_arregion       (subsys_hps_fpga2hps_arregion),                                                //  output,    width = 4,          .arregion
		.m0_arvalid        (subsys_hps_fpga2hps_arvalid),                                                 //  output,    width = 1,          .arvalid
		.m0_arready        (subsys_hps_fpga2hps_arready),                                                 //   input,    width = 1,          .arready
		.m0_rid            (subsys_hps_fpga2hps_rid),                                                     //   input,    width = 5,          .rid
		.m0_rdata          (subsys_hps_fpga2hps_rdata),                                                   //   input,  width = 256,          .rdata
		.m0_rresp          (subsys_hps_fpga2hps_rresp),                                                   //   input,    width = 2,          .rresp
		.m0_rlast          (subsys_hps_fpga2hps_rlast),                                                   //   input,    width = 1,          .rlast
		.m0_rvalid         (subsys_hps_fpga2hps_rvalid),                                                  //   input,    width = 1,          .rvalid
		.m0_rready         (subsys_hps_fpga2hps_rready),                                                  //  output,    width = 1,          .rready
		.m0_ruser          (subsys_hps_fpga2hps_ruser),                                                   //   input,    width = 8,          .ruser
		.s0_awid           (subsys_periph_ssgdma_host_translator_m0_awid),                                //   input,    width = 5,        s0.awid
		.s0_awaddr         (subsys_periph_ssgdma_host_translator_m0_awaddr),                              //   input,   width = 64,          .awaddr
		.s0_awlen          (subsys_periph_ssgdma_host_translator_m0_awlen),                               //   input,    width = 8,          .awlen
		.s0_awsize         (subsys_periph_ssgdma_host_translator_m0_awsize),                              //   input,    width = 3,          .awsize
		.s0_awburst        (subsys_periph_ssgdma_host_translator_m0_awburst),                             //   input,    width = 2,          .awburst
		.s0_awlock         (subsys_periph_ssgdma_host_translator_m0_awlock),                              //   input,    width = 1,          .awlock
		.s0_awcache        (subsys_periph_ssgdma_host_translator_m0_awcache),                             //   input,    width = 4,          .awcache
		.s0_awprot         (subsys_periph_ssgdma_host_translator_m0_awprot),                              //   input,    width = 3,          .awprot
		.s0_awuser         (subsys_periph_ssgdma_host_translator_m0_awuser),                              //   input,    width = 8,          .awuser
		.s0_awqos          (subsys_periph_ssgdma_host_translator_m0_awqos),                               //   input,    width = 4,          .awqos
		.s0_awregion       (subsys_periph_ssgdma_host_translator_m0_awregion),                            //   input,    width = 4,          .awregion
		.s0_awvalid        (subsys_periph_ssgdma_host_translator_m0_awvalid),                             //   input,    width = 1,          .awvalid
		.s0_awready        (subsys_periph_ssgdma_host_translator_m0_awready),                             //  output,    width = 1,          .awready
		.s0_wdata          (subsys_periph_ssgdma_host_translator_m0_wdata),                               //   input,  width = 256,          .wdata
		.s0_wstrb          (subsys_periph_ssgdma_host_translator_m0_wstrb),                               //   input,   width = 32,          .wstrb
		.s0_wlast          (subsys_periph_ssgdma_host_translator_m0_wlast),                               //   input,    width = 1,          .wlast
		.s0_wvalid         (subsys_periph_ssgdma_host_translator_m0_wvalid),                              //   input,    width = 1,          .wvalid
		.s0_wuser          (subsys_periph_ssgdma_host_translator_m0_wuser),                               //   input,    width = 8,          .wuser
		.s0_wready         (subsys_periph_ssgdma_host_translator_m0_wready),                              //  output,    width = 1,          .wready
		.s0_bid            (subsys_periph_ssgdma_host_translator_m0_bid),                                 //  output,    width = 5,          .bid
		.s0_bresp          (subsys_periph_ssgdma_host_translator_m0_bresp),                               //  output,    width = 2,          .bresp
		.s0_buser          (subsys_periph_ssgdma_host_translator_m0_buser),                               //  output,    width = 8,          .buser
		.s0_bvalid         (subsys_periph_ssgdma_host_translator_m0_bvalid),                              //  output,    width = 1,          .bvalid
		.s0_bready         (subsys_periph_ssgdma_host_translator_m0_bready),                              //   input,    width = 1,          .bready
		.s0_arid           (subsys_periph_ssgdma_host_translator_m0_arid),                                //   input,    width = 5,          .arid
		.s0_araddr         (subsys_periph_ssgdma_host_translator_m0_araddr),                              //   input,   width = 64,          .araddr
		.s0_arlen          (subsys_periph_ssgdma_host_translator_m0_arlen),                               //   input,    width = 8,          .arlen
		.s0_arsize         (subsys_periph_ssgdma_host_translator_m0_arsize),                              //   input,    width = 3,          .arsize
		.s0_arburst        (subsys_periph_ssgdma_host_translator_m0_arburst),                             //   input,    width = 2,          .arburst
		.s0_arlock         (subsys_periph_ssgdma_host_translator_m0_arlock),                              //   input,    width = 1,          .arlock
		.s0_arcache        (subsys_periph_ssgdma_host_translator_m0_arcache),                             //   input,    width = 4,          .arcache
		.s0_arprot         (subsys_periph_ssgdma_host_translator_m0_arprot),                              //   input,    width = 3,          .arprot
		.s0_aruser         (subsys_periph_ssgdma_host_translator_m0_aruser),                              //   input,    width = 8,          .aruser
		.s0_arqos          (subsys_periph_ssgdma_host_translator_m0_arqos),                               //   input,    width = 4,          .arqos
		.s0_arregion       (subsys_periph_ssgdma_host_translator_m0_arregion),                            //   input,    width = 4,          .arregion
		.s0_arvalid        (subsys_periph_ssgdma_host_translator_m0_arvalid),                             //   input,    width = 1,          .arvalid
		.s0_arready        (subsys_periph_ssgdma_host_translator_m0_arready),                             //  output,    width = 1,          .arready
		.s0_rid            (subsys_periph_ssgdma_host_translator_m0_rid),                                 //  output,    width = 5,          .rid
		.s0_rdata          (subsys_periph_ssgdma_host_translator_m0_rdata),                               //  output,  width = 256,          .rdata
		.s0_rresp          (subsys_periph_ssgdma_host_translator_m0_rresp),                               //  output,    width = 2,          .rresp
		.s0_rlast          (subsys_periph_ssgdma_host_translator_m0_rlast),                               //  output,    width = 1,          .rlast
		.s0_rvalid         (subsys_periph_ssgdma_host_translator_m0_rvalid),                              //  output,    width = 1,          .rvalid
		.s0_rready         (subsys_periph_ssgdma_host_translator_m0_rready),                              //   input,    width = 1,          .rready
		.s0_ruser          (subsys_periph_ssgdma_host_translator_m0_ruser),                               //  output,    width = 8,          .ruser
		.m0_awuser_addrchk (),                                                                            // (terminated),                         
		.m0_awuser_sai     (),                                                                            // (terminated),                         
		.m0_wuser_datachk  (),                                                                            // (terminated),                         
		.m0_wuser_poison   (),                                                                            // (terminated),                         
		.m0_aruser_addrchk (),                                                                            // (terminated),                         
		.m0_aruser_sai     (),                                                                            // (terminated),                         
		.m0_ruser_datachk  (32'b00000000000000000000000000000000),                                        // (terminated),                         
		.m0_ruser_poison   (4'b0000),                                                                     // (terminated),                         
		.s0_awuser_addrchk (4'b0000),                                                                     // (terminated),                         
		.s0_awuser_sai     (4'b0000),                                                                     // (terminated),                         
		.s0_wuser_datachk  (32'b00000000000000000000000000000000),                                        // (terminated),                         
		.s0_wuser_poison   (4'b0000),                                                                     // (terminated),                         
		.s0_aruser_addrchk (4'b0000),                                                                     // (terminated),                         
		.s0_aruser_sai     (4'b0000),                                                                     // (terminated),                         
		.s0_ruser_datachk  (),                                                                            // (terminated),                         
		.s0_ruser_poison   (),                                                                            // (terminated),                         
		.s0_wid            (5'b00000),                                                                    // (terminated),                         
		.s0_ardomain       (2'b00),                                                                       // (terminated),                         
		.s0_arsnoop        (4'b0000),                                                                     // (terminated),                         
		.s0_arbar          (2'b00),                                                                       // (terminated),                         
		.s0_awdomain       (2'b00),                                                                       // (terminated),                         
		.s0_awsnoop        (3'b000),                                                                      // (terminated),                         
		.s0_awbar          (2'b00),                                                                       // (terminated),                         
		.s0_awunique       (1'b0),                                                                        // (terminated),                         
		.m0_wid            (),                                                                            // (terminated),                         
		.m0_ardomain       (),                                                                            // (terminated),                         
		.m0_arsnoop        (),                                                                            // (terminated),                         
		.m0_arbar          (),                                                                            // (terminated),                         
		.m0_awdomain       (),                                                                            // (terminated),                         
		.m0_awsnoop        (),                                                                            // (terminated),                         
		.m0_awbar          (),                                                                            // (terminated),                         
		.m0_awunique       ()                                                                             // (terminated),                         
	);

endmodule
