// ssgdma_0.v

// Generated using ACDS version 23.4 79

`timescale 1 ps / 1 ps
module ssgdma_0 (
		input  wire         axi_lite_clk,          //       axi_lite_clk.clk
		input  wire         axi_lite_areset_n,     //  axi_lite_areset_n.reset_n
		input  wire         host_clk,              //           host_clk.clk
		input  wire         host_aresetn,          //       host_aresetn.reset_n
		output wire         app_reset_status_n,    // app_reset_status_n.reset_n
		input  wire         host_awready,          //               host.awready
		output wire         host_awvalid,          //                   .awvalid
		output wire [63:0]  host_awaddr,           //                   .awaddr
		output wire [7:0]   host_awlen,            //                   .awlen
		output wire [1:0]   host_awburst,          //                   .awburst
		output wire [2:0]   host_awsize,           //                   .awsize
		output wire [2:0]   host_awprot,           //                   .awprot
		output wire [4:0]   host_awid,             //                   .awid
		output wire [3:0]   host_awcache,          //                   .awcache
		input  wire         host_wready,           //                   .wready
		output wire         host_wvalid,           //                   .wvalid
		output wire [255:0] host_wdata,            //                   .wdata
		output wire [31:0]  host_wstrb,            //                   .wstrb
		output wire         host_wlast,            //                   .wlast
		output wire         host_bready,           //                   .bready
		input  wire         host_bvalid,           //                   .bvalid
		input  wire [1:0]   host_bresp,            //                   .bresp
		input  wire [4:0]   host_bid,              //                   .bid
		input  wire         host_arready,          //                   .arready
		output wire         host_arvalid,          //                   .arvalid
		output wire [63:0]  host_araddr,           //                   .araddr
		output wire [7:0]   host_arlen,            //                   .arlen
		output wire [1:0]   host_arburst,          //                   .arburst
		output wire [2:0]   host_arsize,           //                   .arsize
		output wire [2:0]   host_arprot,           //                   .arprot
		output wire [4:0]   host_arid,             //                   .arid
		output wire [3:0]   host_arcache,          //                   .arcache
		output wire         host_rready,           //                   .rready
		input  wire         host_rvalid,           //                   .rvalid
		input  wire [255:0] host_rdata,            //                   .rdata
		input  wire         host_rlast,            //                   .rlast
		input  wire [1:0]   host_rresp,            //                   .rresp
		input  wire [4:0]   host_rid,              //                   .rid
		output wire         host_lite_csr_awready, //           host_csr.awready
		input  wire         host_lite_csr_awvalid, //                   .awvalid
		input  wire [21:0]  host_lite_csr_awaddr,  //                   .awaddr
		input  wire [2:0]   host_lite_csr_awprot,  //                   .awprot
		output wire         host_lite_csr_wready,  //                   .wready
		input  wire         host_lite_csr_wvalid,  //                   .wvalid
		input  wire [31:0]  host_lite_csr_wdata,   //                   .wdata
		input  wire [3:0]   host_lite_csr_wstrb,   //                   .wstrb
		input  wire         host_lite_csr_bready,  //                   .bready
		output wire         host_lite_csr_bvalid,  //                   .bvalid
		output wire [1:0]   host_lite_csr_bresp,   //                   .bresp
		output wire         host_lite_csr_arready, //                   .arready
		input  wire         host_lite_csr_arvalid, //                   .arvalid
		input  wire [21:0]  host_lite_csr_araddr,  //                   .araddr
		input  wire [2:0]   host_lite_csr_arprot,  //                   .arprot
		input  wire         host_lite_csr_rready,  //                   .rready
		output wire         host_lite_csr_rvalid,  //                   .rvalid
		output wire [31:0]  host_lite_csr_rdata,   //                   .rdata
		output wire [1:0]   host_lite_csr_rresp,   //                   .rresp
		output wire         irq,                   //          interrupt.irq
		input  wire         h2d0_mm_clk,           //        h2d0_mm_clk.clk
		input  wire         h2d0_mm_resetn,        //     h2d0_mm_resetn.reset_n
		output wire         h2d0_awvalid,          //               h2d0.awvalid
		input  wire         h2d0_awready,          //                   .awready
		output wire [63:0]  h2d0_awaddr,           //                   .awaddr
		output wire [7:0]   h2d0_awlen,            //                   .awlen
		output wire [1:0]   h2d0_awburst,          //                   .awburst
		output wire [2:0]   h2d0_awsize,           //                   .awsize
		output wire [2:0]   h2d0_awprot,           //                   .awprot
		output wire [7:0]   h2d0_awid,             //                   .awid
		output wire [3:0]   h2d0_awcache,          //                   .awcache
		output wire         h2d0_wvalid,           //                   .wvalid
		output wire         h2d0_wlast,            //                   .wlast
		input  wire         h2d0_wready,           //                   .wready
		output wire [63:0]  h2d0_wdata,            //                   .wdata
		output wire [7:0]   h2d0_wstrb,            //                   .wstrb
		input  wire         h2d0_bvalid,           //                   .bvalid
		output wire         h2d0_bready,           //                   .bready
		input  wire [1:0]   h2d0_bresp,            //                   .bresp
		input  wire [7:0]   h2d0_bid,              //                   .bid
		output wire         h2d0_arvalid,          //                   .arvalid
		input  wire         h2d0_arready,          //                   .arready
		output wire [63:0]  h2d0_araddr,           //                   .araddr
		output wire [7:0]   h2d0_arlen,            //                   .arlen
		output wire [1:0]   h2d0_arburst,          //                   .arburst
		output wire [2:0]   h2d0_arsize,           //                   .arsize
		output wire [2:0]   h2d0_arprot,           //                   .arprot
		output wire [7:0]   h2d0_arid,             //                   .arid
		output wire [3:0]   h2d0_arcache,          //                   .arcache
		input  wire         h2d0_rvalid,           //                   .rvalid
		input  wire         h2d0_rlast,            //                   .rlast
		output wire         h2d0_rready,           //                   .rready
		input  wire [63:0]  h2d0_rdata,            //                   .rdata
		input  wire [1:0]   h2d0_rresp,            //                   .rresp
		input  wire [7:0]   h2d0_rid               //                   .rid
	);

	intel_ssgdma_top intel_ssgdma_inst (
		.axi_lite_clk          (axi_lite_clk),          //   input,    width = 1,       axi_lite_clk.clk
		.axi_lite_areset_n     (axi_lite_areset_n),     //   input,    width = 1,  axi_lite_areset_n.reset_n
		.host_clk              (host_clk),              //   input,    width = 1,           host_clk.clk
		.host_aresetn          (host_aresetn),          //   input,    width = 1,       host_aresetn.reset_n
		.app_reset_status_n    (app_reset_status_n),    //  output,    width = 1, app_reset_status_n.reset_n
		.host_awready          (host_awready),          //   input,    width = 1,               host.awready
		.host_awvalid          (host_awvalid),          //  output,    width = 1,                   .awvalid
		.host_awaddr           (host_awaddr),           //  output,   width = 64,                   .awaddr
		.host_awlen            (host_awlen),            //  output,    width = 8,                   .awlen
		.host_awburst          (host_awburst),          //  output,    width = 2,                   .awburst
		.host_awsize           (host_awsize),           //  output,    width = 3,                   .awsize
		.host_awprot           (host_awprot),           //  output,    width = 3,                   .awprot
		.host_awid             (host_awid),             //  output,    width = 5,                   .awid
		.host_awcache          (host_awcache),          //  output,    width = 4,                   .awcache
		.host_wready           (host_wready),           //   input,    width = 1,                   .wready
		.host_wvalid           (host_wvalid),           //  output,    width = 1,                   .wvalid
		.host_wdata            (host_wdata),            //  output,  width = 256,                   .wdata
		.host_wstrb            (host_wstrb),            //  output,   width = 32,                   .wstrb
		.host_wlast            (host_wlast),            //  output,    width = 1,                   .wlast
		.host_bready           (host_bready),           //  output,    width = 1,                   .bready
		.host_bvalid           (host_bvalid),           //   input,    width = 1,                   .bvalid
		.host_bresp            (host_bresp),            //   input,    width = 2,                   .bresp
		.host_bid              (host_bid),              //   input,    width = 5,                   .bid
		.host_arready          (host_arready),          //   input,    width = 1,                   .arready
		.host_arvalid          (host_arvalid),          //  output,    width = 1,                   .arvalid
		.host_araddr           (host_araddr),           //  output,   width = 64,                   .araddr
		.host_arlen            (host_arlen),            //  output,    width = 8,                   .arlen
		.host_arburst          (host_arburst),          //  output,    width = 2,                   .arburst
		.host_arsize           (host_arsize),           //  output,    width = 3,                   .arsize
		.host_arprot           (host_arprot),           //  output,    width = 3,                   .arprot
		.host_arid             (host_arid),             //  output,    width = 5,                   .arid
		.host_arcache          (host_arcache),          //  output,    width = 4,                   .arcache
		.host_rready           (host_rready),           //  output,    width = 1,                   .rready
		.host_rvalid           (host_rvalid),           //   input,    width = 1,                   .rvalid
		.host_rdata            (host_rdata),            //   input,  width = 256,                   .rdata
		.host_rlast            (host_rlast),            //   input,    width = 1,                   .rlast
		.host_rresp            (host_rresp),            //   input,    width = 2,                   .rresp
		.host_rid              (host_rid),              //   input,    width = 5,                   .rid
		.host_lite_csr_awready (host_lite_csr_awready), //  output,    width = 1,           host_csr.awready
		.host_lite_csr_awvalid (host_lite_csr_awvalid), //   input,    width = 1,                   .awvalid
		.host_lite_csr_awaddr  (host_lite_csr_awaddr),  //   input,   width = 22,                   .awaddr
		.host_lite_csr_awprot  (host_lite_csr_awprot),  //   input,    width = 3,                   .awprot
		.host_lite_csr_wready  (host_lite_csr_wready),  //  output,    width = 1,                   .wready
		.host_lite_csr_wvalid  (host_lite_csr_wvalid),  //   input,    width = 1,                   .wvalid
		.host_lite_csr_wdata   (host_lite_csr_wdata),   //   input,   width = 32,                   .wdata
		.host_lite_csr_wstrb   (host_lite_csr_wstrb),   //   input,    width = 4,                   .wstrb
		.host_lite_csr_bready  (host_lite_csr_bready),  //   input,    width = 1,                   .bready
		.host_lite_csr_bvalid  (host_lite_csr_bvalid),  //  output,    width = 1,                   .bvalid
		.host_lite_csr_bresp   (host_lite_csr_bresp),   //  output,    width = 2,                   .bresp
		.host_lite_csr_arready (host_lite_csr_arready), //  output,    width = 1,                   .arready
		.host_lite_csr_arvalid (host_lite_csr_arvalid), //   input,    width = 1,                   .arvalid
		.host_lite_csr_araddr  (host_lite_csr_araddr),  //   input,   width = 22,                   .araddr
		.host_lite_csr_arprot  (host_lite_csr_arprot),  //   input,    width = 3,                   .arprot
		.host_lite_csr_rready  (host_lite_csr_rready),  //   input,    width = 1,                   .rready
		.host_lite_csr_rvalid  (host_lite_csr_rvalid),  //  output,    width = 1,                   .rvalid
		.host_lite_csr_rdata   (host_lite_csr_rdata),   //  output,   width = 32,                   .rdata
		.host_lite_csr_rresp   (host_lite_csr_rresp),   //  output,    width = 2,                   .rresp
		.irq                   (irq),                   //  output,    width = 1,          interrupt.irq
		.h2d0_mm_clk           (h2d0_mm_clk),           //   input,    width = 1,        h2d0_mm_clk.clk
		.h2d0_mm_resetn        (h2d0_mm_resetn),        //   input,    width = 1,     h2d0_mm_resetn.reset_n
		.h2d0_awvalid          (h2d0_awvalid),          //  output,    width = 1,               h2d0.awvalid
		.h2d0_awready          (h2d0_awready),          //   input,    width = 1,                   .awready
		.h2d0_awaddr           (h2d0_awaddr),           //  output,   width = 64,                   .awaddr
		.h2d0_awlen            (h2d0_awlen),            //  output,    width = 8,                   .awlen
		.h2d0_awburst          (h2d0_awburst),          //  output,    width = 2,                   .awburst
		.h2d0_awsize           (h2d0_awsize),           //  output,    width = 3,                   .awsize
		.h2d0_awprot           (h2d0_awprot),           //  output,    width = 3,                   .awprot
		.h2d0_awid             (h2d0_awid),             //  output,    width = 8,                   .awid
		.h2d0_awcache          (h2d0_awcache),          //  output,    width = 4,                   .awcache
		.h2d0_wvalid           (h2d0_wvalid),           //  output,    width = 1,                   .wvalid
		.h2d0_wlast            (h2d0_wlast),            //  output,    width = 1,                   .wlast
		.h2d0_wready           (h2d0_wready),           //   input,    width = 1,                   .wready
		.h2d0_wdata            (h2d0_wdata),            //  output,   width = 64,                   .wdata
		.h2d0_wstrb            (h2d0_wstrb),            //  output,    width = 8,                   .wstrb
		.h2d0_bvalid           (h2d0_bvalid),           //   input,    width = 1,                   .bvalid
		.h2d0_bready           (h2d0_bready),           //  output,    width = 1,                   .bready
		.h2d0_bresp            (h2d0_bresp),            //   input,    width = 2,                   .bresp
		.h2d0_bid              (h2d0_bid),              //   input,    width = 8,                   .bid
		.h2d0_arvalid          (h2d0_arvalid),          //  output,    width = 1,                   .arvalid
		.h2d0_arready          (h2d0_arready),          //   input,    width = 1,                   .arready
		.h2d0_araddr           (h2d0_araddr),           //  output,   width = 64,                   .araddr
		.h2d0_arlen            (h2d0_arlen),            //  output,    width = 8,                   .arlen
		.h2d0_arburst          (h2d0_arburst),          //  output,    width = 2,                   .arburst
		.h2d0_arsize           (h2d0_arsize),           //  output,    width = 3,                   .arsize
		.h2d0_arprot           (h2d0_arprot),           //  output,    width = 3,                   .arprot
		.h2d0_arid             (h2d0_arid),             //  output,    width = 8,                   .arid
		.h2d0_arcache          (h2d0_arcache),          //  output,    width = 4,                   .arcache
		.h2d0_rvalid           (h2d0_rvalid),           //   input,    width = 1,                   .rvalid
		.h2d0_rlast            (h2d0_rlast),            //   input,    width = 1,                   .rlast
		.h2d0_rready           (h2d0_rready),           //  output,    width = 1,                   .rready
		.h2d0_rdata            (h2d0_rdata),            //   input,   width = 64,                   .rdata
		.h2d0_rresp            (h2d0_rresp),            //   input,    width = 2,                   .rresp
		.h2d0_rid              (h2d0_rid)               //   input,    width = 8,                   .rid
	);

endmodule
